# Generated by Django 3.1.2 on 2020-10-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('curva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curvas.curva')),
            ],
        ),
    ]
