# Generated by Django 3.1.2 on 2020-10-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number_pages', models.IntegerField()),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
