# Generated by Django 3.1.2 on 2020-10-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201020_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='book',
            name='unit_price',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=128), null=True),
        ),
    ]
