# Generated by Django 3.1.2 on 2020-10-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20201021_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='unit_price_sell',
            new_name='sell_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='unit_price',
        ),
    ]
